name: pgai
services:
  pg16:
    build:
      context: .
      dockerfile: _db.dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
  tsdb:
    build:
      context: .
      dockerfile: _tsdb.dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:v0.2.1
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
volumes:
  data: