INSERT INTO public.almaden_knowledge
(id, problem, solution, created_at, updated_at)
VALUES
(1, 'High CPU Usage on Slack', 'Close unnecessary channels and integrations, update Slack to the latest version, and reduce the number of concurrent open threads.', NOW(), NOW()),
(2, 'Delayed Email Notifications in Teams', 'Check notification settings and ensure the user is properly subscribed to the relevant channels. Clear cache and check for service outages.', NOW(), NOW()),
(3, 'Outlook Not Syncing with Exchange Server', 'Check internet connection, reconfigure the email account, and ensure Exchange server is up. Clear credentials and reset sync settings.', NOW(), NOW()),
(4, 'Slow Performance in Workday', 'Clear browser cache and cookies, update browser, and ensure proper network connectivity. Consider using a different browser or device for optimal performance.', NOW(), NOW()),
(5, 'Frequent VPN Disconnects during Remote Work', 'Update VPN client software, check network strength, and ensure VPN server is stable. Reduce unnecessary background applications.', NOW(), NOW()),
(6, 'Unable to Share Files in Microsoft Teams', 'Ensure correct permissions are set for file sharing. Clear Teams cache, and check whether storage limits have been exceeded.', NOW(), NOW()),
(7, 'Microsoft OneDrive Sync Issues', 'Ensure OneDrive is up-to-date, check the local storage capacity, and restart the sync client. Verify that no conflicting sync processes are running.', NOW(), NOW()),
(8, 'Audio/Video Quality Issues in Zoom Calls', 'Test internet connection speed, close unnecessary applications, and update Zoom client to the latest version. Check camera and microphone settings.', NOW(), NOW()),
(9, 'Inconsistent Search Results in SharePoint', 'Ensure correct indexing settings are enabled, refresh the search index, and check if the document libraries are properly configured for search.', NOW(), NOW()),
(10, 'Slack Messages Not Syncing across Devices', 'Sign out and sign back in to Slack, check internet connection, and ensure Slack is updated on all devices.', NOW(), NOW()),
(11, 'Teams Meeting Recording Failed', 'Verify that the meeting organizer has the correct permissions, check for available storage space in Microsoft Stream, and ensure the Teams client is updated.', NOW(), NOW()),
(12, 'Slow Login Times in Okta', 'Clear browser cache and cookies, check Okta configuration settings, and review login policies. Check the network latency as well.', NOW(), NOW()),
(13, 'Unable to Connect to Microsoft Exchange Server', 'Check email client configurations, test network connectivity, and ensure Exchange server is reachable. Restart email application.', NOW(), NOW()),
(14, 'Issue with Permissions in Google Drive', 'Verify user permissions and access control settings. Ensure that the user has sufficient rights to perform the required actions.', NOW(), NOW()),
(15, 'Slowness in ServiceNow', 'Clear cache and cookies, verify network stability, and ensure the application is properly configured for the user’s role. Reduce unnecessary background processes.', NOW(), NOW()),
(16, 'Problems with Google Meet Video Freezing', 'Check internet speed, close other applications consuming bandwidth, update the Google Meet app, and test on a different device.', NOW(), NOW()),
(17, 'Employee Portal Access Denied', 'Verify user credentials, check for expired passwords, and confirm account permissions. Check the server-side configurations and clear browser cache.', NOW(), NOW()),
(18, 'Disconnected from Zoom Breakout Room', 'Check internet connection, verify the breakout room setup, and rejoin the meeting if needed. Ensure Zoom client is up to date.', NOW(), NOW()),
(19, 'Login Issues with HRIS System', 'Reset user password, check account status, and review login configurations. Clear cache and cookies and try a different browser.', NOW(), NOW()),
(20, 'Slack Notifications Not Showing on Mobile', 'Check mobile device notification settings and ensure Slack notifications are enabled in the app. Reinstall the Slack app if necessary.', NOW(), NOW()),
(21, 'Teams Video Call Lag', 'Close unused apps, check the internet speed, and ensure the system meets Teams’ hardware requirements. Restart the Teams app if needed.', NOW(), NOW()),
(22, 'Issues with Microsoft Word AutoSave', 'Ensure OneDrive or SharePoint syncing is enabled, check storage space, and verify the file format supports AutoSave functionality.', NOW(), NOW()),
(23, 'Slow File Uploads in Google Drive', 'Check internet connection speed, avoid large file uploads during peak hours, and ensure Google Drive is up to date.', NOW(), NOW()),
(24, 'Error Saving Data in CRM System', 'Verify user permissions, check if the data exceeds system limits, and ensure that the CRM system is connected to the database.', NOW(), NOW()),
(25, 'Teams App Crashes on Startup', 'Update Teams app to the latest version, restart the computer, and check if other applications are interfering with the Teams client.', NOW(), NOW()),
(26, 'Dropbox File Syncing Issues', 'Ensure Dropbox is properly configured, check if the file path exceeds the maximum length, and make sure there’s enough local storage space.', NOW(), NOW()),
(27, 'Unresponsive Microsoft SharePoint Site', 'Check for server-side issues, clear browser cache, ensure network connectivity, and verify if the site collection is still active.', NOW(), NOW()),
(28, 'Google Workspace Document Permissions Not Updating', 'Check for sync issues between Google Workspace and local devices, ensure user permissions are set correctly, and refresh the document.', NOW(), NOW()),
(29, 'Teams Screen Share Not Working', 'Ensure Teams is updated, check camera and screen-sharing permissions, and test with different screen content to see if the issue persists.', NOW(), NOW()),
(30, 'Microsoft Edge Crashing with Work Apps', 'Clear browser cache, disable unnecessary extensions, and update Microsoft Edge. Test the issue in an incognito window or different browser.', NOW(), NOW()),
(31, 'Unable to Join Zoom Meeting', 'Ensure the meeting link is valid, verify user permissions, check Zoom app version, and test on a different device if needed.', NOW(), NOW()),
(32, 'Problems with Microsoft Planner Syncing', 'Check internet connection, ensure the Planner app is up to date, and check for integration issues between Planner and other Microsoft services.', NOW(), NOW()),
(33, 'Error Logging into Jira', 'Verify login credentials, check Jira system status, and clear browser cache. Review Jira’s security settings to confirm they are not blocking access.', NOW(), NOW()),
(34, 'Microsoft Teams Audio Not Working', 'Check microphone and speaker settings, ensure Teams permissions are configured correctly, and update the Teams app to the latest version.', NOW(), NOW()),
(35, 'Google Meet Freezes During Meeting', 'Test internet connection speed, close unnecessary apps, and make sure Google Meet is updated. Try switching to a different network if possible.', NOW(), NOW()),
(36, 'VPN Access Denied', 'Verify VPN login credentials, check for system updates, and confirm that the VPN service is not blocked by a firewall or network policy.', NOW(), NOW()),
(37, 'Outlook Calendar Sync Issues', 'Ensure the correct time zone settings, check the server status, and reconfigure account settings if necessary. Restart Outlook and refresh the calendar.', NOW(), NOW()),
(38, 'Teams Channel Messages Not Posting', 'Check user permissions, refresh the Teams app, and ensure that the channel is not muted or restricted.', NOW(), NOW()),
(39, 'Unable to Upload Files to SharePoint', 'Check file size limits, ensure the user has the correct permissions, and confirm there is no ongoing SharePoint outage.', NOW(), NOW()),
(40, 'Microsoft OneNote Not Syncing', 'Check OneDrive syncing settings, ensure the latest version of OneNote is installed, and confirm that the file is within sync limits.', NOW(), NOW()),
(41, 'Google Drive Not Loading Files', 'Ensure Google Drive is not experiencing an outage, check internet connection, and confirm the file format is supported for viewing.', NOW(), NOW()),
(42, 'Unable to Send Emails in Gmail', 'Check email client configurations, ensure the account is correctly authenticated, and review Google’s service status for outages.', NOW(), NOW()),
(43, 'Trello Board Not Updating', 'Check for connectivity issues, ensure the Trello app is up-to-date, and clear the browser cache.', NOW(), NOW()),
(44, 'SAML Authentication Error in Okta', 'Ensure correct configuration of the SAML integration, verify that the metadata file is up to date, and check for expired certificates.', NOW(), NOW()),
(45, 'Unable to View Documents in Confluence', 'Ensure user has the correct permissions, check for browser compatibility issues, and refresh the page or try in incognito mode.', NOW(), NOW()),
(46, 'Chat Notifications Not Showing on Slack', 'Ensure that the Slack app’s notification settings are enabled, check mobile device settings, and update the app if necessary.', NOW(), NOW()),
(47, 'Microsoft Word Crashing on Save', 'Check for conflicting add-ins, ensure that the document is saved to a supported location, and update Office suite to the latest version.', NOW(), NOW()),
(48, 'Not Able to Schedule Teams Meeting', 'Check user permissions for scheduling meetings, ensure calendar integration is set up correctly, and update Teams to the latest version.', NOW(), NOW()),
(49, 'Error Accessing HRMS Application', 'Check network connectivity, verify user credentials, and ensure there are no maintenance windows scheduled for the HRMS system.', NOW(), NOW()),
(50, 'Google Calendar Sync Issues', 'Ensure the calendar settings are correctly configured, check for API syncing issues, and refresh the calendar.', NOW(), NOW()),
(51, 'Workday App Freezing', 'Clear browser cache and cookies, update the app to the latest version, and check for network issues.', NOW(), NOW()),
(52, 'Teams App Not Loading', 'Check if Teams is down for maintenance, clear Teams app cache, and reinstall the app if necessary.', NOW(), NOW()),
(53, 'Unable to Connect to Work VPN', 'Verify VPN credentials, check for server issues, and confirm that firewall settings are not blocking the VPN connection.', NOW(), NOW()),
(54, 'Google Drive Storage Limit Reached', 'Clear unnecessary files, purchase additional storage, or move files to an external drive. Review storage consumption patterns.', NOW(), NOW()),
(55, 'WebEx Connection Issues during Meetings', 'Check internet speed, ensure WebEx is up-to-date, and test connection with other devices or networks.', NOW(), NOW()),
(56, 'Microsoft Teams Calendar Not Showing', 'Ensure Teams is synced with Outlook calendar, check permissions for viewing calendars, and refresh the Teams app.', NOW(), NOW()),
(57, 'Poor Audio Quality on Microsoft Teams', 'Test microphone and speaker setup, close unused apps, and check for network issues. Update Teams client to the latest version.', NOW(), NOW()),
(58, 'Password Expiry Notification Not Received', 'Ensure correct notification settings are configured in Active Directory, and check email spam/junk folders.', NOW(), NOW()),
(59, 'Unable to Log into Zendesk', 'Verify login credentials, check for service outages, and ensure the user has the correct role-based permissions.', NOW(), NOW()),
(60, 'Teams File Sharing Not Working', 'Check permissions for the shared file, ensure the file type is supported, and confirm Teams app is updated.', NOW(), NOW()),
(61, 'Outlook Calendar Events Missing', 'Verify synchronization settings, check for calendar conflicts, and update the Outlook client if necessary.', NOW(), NOW()),
(62, 'Box File Sharing Issues', 'Verify user access permissions, check for sync issues, and ensure Box app is updated to the latest version.', NOW(), NOW()),
(63, 'Unable to Open PDF Files in Microsoft Teams', 'Ensure the correct PDF viewer is installed, check for file permissions, and update Teams to the latest version.', NOW(), NOW()),
(64, 'Error with Mobile Authentication in Okta', 'Check Okta mobile app configurations, verify device security settings, and ensure proper integration with the identity provider.', NOW(), NOW()),
(65, 'Website Performance Issues on Company Intranet', 'Verify server load and traffic, check for content delivery network (CDN) issues, and ensure the intranet platform is up-to-date.', NOW(), NOW()),
(66, 'Google Meet Unable to Record', 'Check user permissions, ensure Google Meet recording feature is enabled in admin settings, and confirm storage availability in Google Drive.', NOW(), NOW()),
(67, 'Low Battery on Company Laptop', 'Optimize power settings, close unnecessary applications, and ensure the latest power-saving updates are installed.', NOW(), NOW()),
(68, 'Slack DMs Not Syncing Across Devices', 'Ensure Slack is updated on all devices, sign out and back in, and check internet connection for sync issues.', NOW(), NOW()),
(69, 'Slow Access to Cloud Files in Dropbox', 'Check for syncing issues, update Dropbox app, and confirm there are no server-side outages affecting the service.', NOW(), NOW()),
(70, 'Error Editing Files in Google Docs', 'Check for conflicting edits, ensure the file is not locked by another user, and confirm that the Google Docs app is updated.', NOW(), NOW()),
(71, 'Unable to Access Files in SharePoint', 'Verify user permissions, ensure the document library is accessible, and check for system outages on SharePoint.', NOW(), NOW()),
(72, 'Zoom Video Call Not Starting', 'Check user permissions, ensure Zoom app is up-to-date, and verify the meeting link is correct.', NOW(), NOW()),
(73, 'Unable to Send Notifications in ServiceNow', 'Check user notification preferences, verify that the system is configured to send notifications, and ensure ServiceNow is up-to-date.', NOW(), NOW()),
(74, 'Unable to Download Files from Microsoft Teams', 'Check for file permissions, ensure the file is supported, and confirm Teams app is up to date.', NOW(), NOW()),
(75, 'Teams Notification Not Triggering on Mobile', 'Ensure Teams mobile app notifications are enabled, check Do Not Disturb mode, and reinstall the app if needed.', NOW(), NOW()),
(76, 'Dropbox Not Syncing Files Automatically', 'Check the Dropbox app’s sync settings, ensure the app is running in the background, and verify there are no ongoing outages.', NOW(), NOW()),
(77, 'Unable to Connect to Company Wi-Fi', 'Ensure Wi-Fi credentials are correct, check router status, and confirm there are no issues with network configuration or bandwidth limits.', NOW(), NOW()),
(78, 'Gmail Not Sending Emails from Mobile', 'Verify Gmail app permissions, check if email size exceeds limits, and update Gmail app to the latest version.', NOW(), NOW()),
(79, 'Trello Card Not Moving to List', 'Check for card permission issues, refresh the page, and ensure the list is not locked by an administrator.', NOW(), NOW()),
(80, 'Microsoft Teams Outage', 'Check Microsoft 365 service status page, verify that there are no ongoing outages affecting Teams services, and wait for service restoration.', NOW(), NOW()),
(81, 'Unable to Log into Salesforce', 'Verify login credentials, check for system outages, and confirm user permissions are correctly set in Salesforce.', NOW(), NOW()),
(82, 'Performance Issues in Atlassian Confluence', 'Check for server-side issues, reduce page load by optimizing content, and ensure Confluence is updated to the latest version.', NOW(), NOW()),
(83, 'Workday Not Loading on Mobile', 'Check mobile app version, ensure that the internet connection is stable, and verify that the Workday app has the necessary permissions on your device.', NOW(), NOW()),
(84, 'Zoom Meeting Not Showing in Calendar', 'Ensure Zoom calendar integration is enabled, check calendar permissions, and verify meeting invite was properly sent.', NOW(), NOW()),
(85, 'Unable to Join Skype for Business Meeting', 'Ensure Skype for Business is up-to-date, check permissions, and confirm meeting link validity.', NOW(), NOW()),
(86, 'Slack Message Delivery Delay', 'Check network latency, verify Slack server status, and ensure there are no service disruptions affecting message delivery.', NOW(), NOW()),
(87, 'SAML Integration Issues with Okta', 'Ensure correct SAML configuration, check metadata files for errors, and verify the identity provider is properly configured.', NOW(), NOW()),
(88, 'No Access to Google Sheets', 'Ensure the correct permissions are set for the sheet, check network connectivity, and confirm that the file is shared correctly.', NOW(), NOW()),
(89, 'Unable to Upload Photos to Microsoft Teams', 'Check file size, ensure correct permissions, and confirm that the Teams app is updated.', NOW(), NOW()),
(90, 'ServiceNow API Timeout', 'Check API endpoint configurations, ensure no server-side issues are causing timeouts, and verify network connectivity.', NOW(), NOW()),
(91, 'Microsoft Teams Desktop App Not Opening', 'Check system requirements, update Teams app, and clear cache. Reinstall the app if necessary.', NOW(), NOW()),
(92, 'Google Meet Screen Sharing Not Working', 'Check browser permissions, ensure the app is up-to-date, and test with different screen-sharing content.', NOW(), NOW()),
(93, 'Slack User Profile Not Updating', 'Ensure the app is updated, clear cache, and check if profile updates are restricted by company policies.', NOW(), NOW()),
(94, 'Unable to Find Documents in Confluence', 'Ensure the correct search filters are applied, check for indexing issues, and confirm the page/document permissions are correctly set.', NOW(), NOW()),
(95, 'Slack Message Not Displaying in Search', 'Check for message privacy settings, ensure the message is not archived, and confirm Slack indexing is up-to-date.', NOW(), NOW()),
(96, 'ServiceNow Login Not Working', 'Check login credentials, clear browser cache, and confirm that ServiceNow is not experiencing an outage.', NOW(), NOW()),
(97, 'Google Meet Unable to Join via Link', 'Verify meeting link validity, check user permissions, and ensure that the Google Meet app is properly configured.', NOW(), NOW()),
(98, 'Delayed Responses in ChatBot', 'Check server-side processing time, reduce unnecessary background tasks, and verify chatbot integration with backend systems.', NOW(), NOW()),
(99, 'No Access to Company Intranet', 'Check internet connection, verify company VPN settings, and ensure that the intranet service is not down.', NOW(), NOW()),
(100, 'Unable to Share Screen in Google Meet', 'Check screen-sharing permissions, update Google Meet, and ensure that the browser supports screen sharing.', NOW(), NOW());
